apiVersion: v1
kind: Service
metadata:
  name: katalog
  labels:
    app: katalog
spec:
  selector:
    app: katalog
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
